name: Sync main to ran_main

on:
  push:
    branches:
      - main  # Runs when pushing to main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"

      - name: Fetch all branches
        run: git fetch --all

      - name: Switch to ran_main
        run: |
          git checkout ran_main || git checkout -b ran_main origin/ran_main
          git merge --ff-only main || (echo "Merge conflict, aborting" && exit 1)

      - name: Push changes to ran_main
        run: git push origin ran_main
